### YamlMime:ManagedReference
items:
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration
  commentId: T:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration
  id: CameraConfiguration
  parent: GHIElectronics.Endpoint.Devices.Camera
  children:
  - GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.FrameRate
  - GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Height
  - GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.ImageFormat
  - GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Width
  langs:
  - csharp
  - vb
  name: CameraConfiguration
  nameWithType: CameraConfiguration
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration
  type: Class
  source:
    remote:
      path: Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
      branch: add_ui
      repo: https://github.com/ghi-electronics/Endpoint-Libraries.git
    id: CameraConfiguration
    path: ../Endpoint-Libraries/Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
    startLine: 13
  assemblies:
  - GHIElectronics.Endpoint.Devices.Camera
  namespace: GHIElectronics.Endpoint.Devices.Camera
  syntax:
    content: public class CameraConfiguration
    content.vb: Public Class CameraConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Width
  commentId: P:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Width
  id: Width
  parent: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration
  langs:
  - csharp
  - vb
  name: Width
  nameWithType: CameraConfiguration.Width
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Width
  type: Property
  source:
    remote:
      path: Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
      branch: add_ui
      repo: https://github.com/ghi-electronics/Endpoint-Libraries.git
    id: Width
    path: ../Endpoint-Libraries/Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
    startLine: 14
  assemblies:
  - GHIElectronics.Endpoint.Devices.Camera
  namespace: GHIElectronics.Endpoint.Devices.Camera
  syntax:
    content: public int Width { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Width As Integer
  overload: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Width*
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Height
  commentId: P:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Height
  id: Height
  parent: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration
  langs:
  - csharp
  - vb
  name: Height
  nameWithType: CameraConfiguration.Height
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Height
  type: Property
  source:
    remote:
      path: Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
      branch: add_ui
      repo: https://github.com/ghi-electronics/Endpoint-Libraries.git
    id: Height
    path: ../Endpoint-Libraries/Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
    startLine: 15
  assemblies:
  - GHIElectronics.Endpoint.Devices.Camera
  namespace: GHIElectronics.Endpoint.Devices.Camera
  syntax:
    content: public int Height { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Height As Integer
  overload: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Height*
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.ImageFormat
  commentId: P:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.ImageFormat
  id: ImageFormat
  parent: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration
  langs:
  - csharp
  - vb
  name: ImageFormat
  nameWithType: CameraConfiguration.ImageFormat
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.ImageFormat
  type: Property
  source:
    remote:
      path: Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
      branch: add_ui
      repo: https://github.com/ghi-electronics/Endpoint-Libraries.git
    id: ImageFormat
    path: ../Endpoint-Libraries/Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
    startLine: 16
  assemblies:
  - GHIElectronics.Endpoint.Devices.Camera
  namespace: GHIElectronics.Endpoint.Devices.Camera
  syntax:
    content: public Format ImageFormat { get; set; }
    parameters: []
    return:
      type: GHIElectronics.Endpoint.Devices.Camera.Format
    content.vb: Public Property ImageFormat As Format
  overload: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.ImageFormat*
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.FrameRate
  commentId: P:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.FrameRate
  id: FrameRate
  parent: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration
  langs:
  - csharp
  - vb
  name: FrameRate
  nameWithType: CameraConfiguration.FrameRate
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.FrameRate
  type: Property
  source:
    remote:
      path: Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
      branch: add_ui
      repo: https://github.com/ghi-electronics/Endpoint-Libraries.git
    id: FrameRate
    path: ../Endpoint-Libraries/Dotnet/GHIElectronics.Endpoint.Libraries/GHIElectronics.Endpoint.Devices.Camera/Camera.cs
    startLine: 18
  assemblies:
  - GHIElectronics.Endpoint.Devices.Camera
  namespace: GHIElectronics.Endpoint.Devices.Camera
  syntax:
    content: public int FrameRate { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property FrameRate As Integer
  overload: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.FrameRate*
references:
- uid: GHIElectronics.Endpoint.Devices.Camera
  commentId: N:GHIElectronics.Endpoint.Devices.Camera
  href: GHIElectronics.html
  name: GHIElectronics.Endpoint.Devices.Camera
  nameWithType: GHIElectronics.Endpoint.Devices.Camera
  fullName: GHIElectronics.Endpoint.Devices.Camera
  spec.csharp:
  - uid: GHIElectronics
    name: GHIElectronics
    href: GHIElectronics.html
  - name: .
  - uid: GHIElectronics.Endpoint
    name: Endpoint
    href: GHIElectronics.Endpoint.html
  - name: .
  - uid: GHIElectronics.Endpoint.Devices
    name: Devices
    href: GHIElectronics.Endpoint.Devices.html
  - name: .
  - uid: GHIElectronics.Endpoint.Devices.Camera
    name: Camera
    href: GHIElectronics.Endpoint.Devices.Camera.html
  spec.vb:
  - uid: GHIElectronics
    name: GHIElectronics
    href: GHIElectronics.html
  - name: .
  - uid: GHIElectronics.Endpoint
    name: Endpoint
    href: GHIElectronics.Endpoint.html
  - name: .
  - uid: GHIElectronics.Endpoint.Devices
    name: Devices
    href: GHIElectronics.Endpoint.Devices.html
  - name: .
  - uid: GHIElectronics.Endpoint.Devices.Camera
    name: Camera
    href: GHIElectronics.Endpoint.Devices.Camera.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Width*
  commentId: Overload:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Width
  href: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.html#GHIElectronics_Endpoint_Devices_Camera_CameraConfiguration_Width
  name: Width
  nameWithType: CameraConfiguration.Width
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Width
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Height*
  commentId: Overload:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Height
  href: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.html#GHIElectronics_Endpoint_Devices_Camera_CameraConfiguration_Height
  name: Height
  nameWithType: CameraConfiguration.Height
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.Height
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.ImageFormat*
  commentId: Overload:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.ImageFormat
  href: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.html#GHIElectronics_Endpoint_Devices_Camera_CameraConfiguration_ImageFormat
  name: ImageFormat
  nameWithType: CameraConfiguration.ImageFormat
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.ImageFormat
- uid: GHIElectronics.Endpoint.Devices.Camera.Format
  commentId: T:GHIElectronics.Endpoint.Devices.Camera.Format
  parent: GHIElectronics.Endpoint.Devices.Camera
  href: GHIElectronics.Endpoint.Devices.Camera.Format.html
  name: Format
  nameWithType: Format
  fullName: GHIElectronics.Endpoint.Devices.Camera.Format
- uid: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.FrameRate*
  commentId: Overload:GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.FrameRate
  href: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.html#GHIElectronics_Endpoint_Devices_Camera_CameraConfiguration_FrameRate
  name: FrameRate
  nameWithType: CameraConfiguration.FrameRate
  fullName: GHIElectronics.Endpoint.Devices.Camera.CameraConfiguration.FrameRate
